# Generated by Django 2.1.1 on 2018-09-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccopc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
