# Generated by Django 2.1.1 on 2018-09-21 19:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccopc', '0006_auto_20180920_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
