# Generated by Django 2.1.1 on 2018-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccopc', '0010_auto_20180923_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='gwarancja',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
